bash data_collection/bashs/weather-0/routes_town03_long.sh & 
bash data_collection/bashs/weather-1/routes_town03_long.sh & 
bash data_collection/bashs/weather-2/routes_town03_long.sh & 
bash data_collection/bashs/weather-3/routes_town03_long.sh & 
bash data_collection/bashs/weather-4/routes_town03_long.sh & 
bash data_collection/bashs/weather-5/routes_town03_long.sh & 
bash data_collection/bashs/weather-6/routes_town03_long.sh & 
bash data_collection/bashs/weather-7/routes_town03_long.sh & 
bash data_collection/bashs/weather-8/routes_town03_long.sh & 
bash data_collection/bashs/weather-9/routes_town03_long.sh & 
bash data_collection/bashs/weather-10/routes_town03_long.sh & 
bash data_collection/bashs/weather-11/routes_town03_long.sh & 
bash data_collection/bashs/weather-12/routes_town03_long.sh & 
bash data_collection/bashs/weather-13/routes_town03_long.sh & 
